pool: MyAgentPool
steps:
- bash: echo hello world

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.5' # specify the version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
